apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap-config.yaml
  - configmap-workspace.yaml
  # - configmap-cron.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

secretGenerator:
- name: openclaw-secrets
  namespace: openclaw
  envs:
  - .env.secrets
  options:
    disableNameSuffixHash: true
