kind: Secret
apiVersion: v1
metadata:
  name: secrets-rhdh
  namespace: backstage
data:
  BACKEND_SECRET: c2VsZnNlcnZlLXBvcnRhbAo= # echo self-serve | base64
  GITHUB_ORG: "my-gh-org"
  GITHUB_CLIENT_ID: "my GH client ID"
  GITHUB_CLIENT_SECRET: "my GH client secret"
  GITHUB_TOKEN: "my GH developer token"
  AUTH_GITHUB_APP_ID: "app id"
  AUTH_GITHUB_CLIENT_ID: "my GH client ID"
  GITHUB_HOST_DOMAIN: "github.com"
  GITHUB_ORGANIZATION: "alinahid477"
  GITHUB_ORG_URL: "https://github.com/alinahid477"
  GITHUB_PRIVATE_KEY_FILE: "Enter the saved Private key."
  GITHUB_WEBHOOK_URL: "https://backstage-selfserve-portal-backstage.apps.metalsno.home.alishomelab.site"
  GITHUB_WEBHOOK_SECRET: "Enter the saved Webhook secret."
type: Opaque

# oc get secret default-token -n backstage -o jsonpath='{.data.token}' | base64 --decode