apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: selfserve-portal
  namespace: backstage
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
    extraFiles:
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    replicas: 1
    extraEnvs:
      envs:
        # Disabling TLS verification
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
      secrets:
        - name: secrets-rhdh
    route:
      enabled: true
  database:
    enableLocalDb: true